import layers
from conv_net_contact_map import ConvNetContactMapBase, ConvNetContactMap
from encode_decode import EncodeDecodeContactMap
from atrous_conv import AtrousConvContactMap
from custom_atrous_conv import CustomAtrousConvContactMap
from raptorx_copy import RaptorX_structure