import layers
from conv_net_contact_map import ConvNetContactMapBase, ConvNetContactMap
#from conv_net_contact_map_torch import ConvNetContactMapTorch
from encode_decode import EncodeDecodeContactMap
from atrous_conv import AtrousConvContactMap
#from diag_atrous_conv import DiagAtrousConvContactMap
