#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri May 26 12:19:12 2017

@author: zqwu
"""

import numpy as np
import os
import Bio
import tempfile
import pnet

from Bio.Blast.Applications import NcbiblastpCommandline
from Bio.Blast import NCBIXML

def blastp(seq, database='nr'):
  save_dir = tempfile.mkdtemp()
  pnet.utils.write_sequence(seq, os.path.join(save_dir, 'temp.seq'))
  result = Bio.Blast.NCBIWWW.qblast("blastp", database, seq)
  blast_records = NCBIXML.parse(result)
  
def blastp_local(seq, database='nr', data_dir=None):
  save_dir = tempfile.mkdtemp()
  pnet.utils.write_sequence(seq, os.path.join(save_dir, 'temp.seq'))
  if data_dir is None:
    data_dir = os.environ['BLAST_DATA_DIR']
  cline = NcbiblastpCommandline(query=os.path.join(save_dir, 'temp.seq'), 
                                db=os.path.join(data_dir, database), 
                                out=os.path.join(save_dir, 'results.xml'),
                                evalue=0.001)
  stdout, stderr = cline()
  
  
  
def psiblast_local(seq, database='nr', data_dir=None):
  save_dir = tempfile.mkdtemp()
  pnet.utils.write_sequence(seq, os.path.join(save_dir, 'temp.seq'))
  if data_dir is None:
    data_dir = os.environ['BLAST_DATA_DIR']
  cline = NcbipsiblastCommandline(query=os.path.join(save_dir, 'temp.seq'), 
                                  db=os.path.join(data_dir, database), 
                                  out=os.path.join(save_dir, 'results.xml'),
                                  evalue=0.001)
  stdout, stderr = cline()
  
  
def system_call(command):
  p = subprocess.Popen([command], stdout=subprocess.PIPE, shell=True)
  return p.stdout.read()